<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TravelPackageSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('travel_packages')->insert([
            [
                'slug' => 'bali-escape',
                'title' => 'Bandung Barat Escape',
                'category' => 'Beach',
                'summary' => 'Paket 3 hari 2 malam untuk menikmati udara sejuk, kuliner, dan wisata alam Bandung Barat.',
                'description' => 'Paket wisata Bandung Barat dengan kombinasi destinasi alam, kuliner, dan pengalaman santai yang nyaman untuk pasangan maupun keluarga.',
                'featured_image' => 'product-8.jpg',
                'base_price' => 120.00,
                'sale_price' => 80.00,
                'duration_days' => 3,
                'quota' => 12,
                'location' => 'Bandung Barat',
                'is_featured' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'bandung-retreat',
                'title' => 'Bandung Retreat',
                'category' => 'Family',
                'summary' => 'Perjalanan santai untuk keluarga dengan destinasi alam dan kuliner Bandung Barat.',
                'description' => 'Cocok untuk keluarga yang ingin menikmati udara sejuk, wisata alam, dan kuliner khas Bandung Barat.',
                'featured_image' => 'product-9.jpg',
                'base_price' => 120.00,
                'sale_price' => null,
                'duration_days' => 2,
                'quota' => 20,
                'location' => 'Bandung Barat',
                'is_featured' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'bromo-sunrise',
                'title' => 'Lembang Sunrise',
                'category' => 'Adventure',
                'summary' => 'Nikmati sunrise terbaik dari kawasan Lembang dengan transport aman.',
                'description' => 'Open trip favorit untuk traveler yang ingin menikmati sunrise Bandung Barat dengan pengalaman singkat namun berkesan.',
                'featured_image' => 'product-10.jpg',
                'base_price' => 120.00,
                'sale_price' => null,
                'duration_days' => 2,
                'quota' => 8,
                'location' => 'Lembang',
                'is_featured' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'yogyakarta-heritage',
                'title' => 'Bandung Barat Heritage',
                'category' => 'Culture',
                'summary' => 'Wisata budaya ke desa wisata, kebun, dan sentra kreatif lokal.',
                'description' => 'Paket budaya dan alam dengan destinasi ikonik Bandung Barat yang cocok untuk itinerary edukatif.',
                'featured_image' => 'product-11.jpg',
                'base_price' => 120.00,
                'sale_price' => null,
                'duration_days' => 3,
                'quota' => 14,
                'location' => 'Bandung Barat',
                'is_featured' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'labuan-bajo-sailing',
                'title' => 'Bandung Barat Nature Stay',
                'category' => 'Adventure',
                'summary' => 'Paket premium untuk traveler yang ingin eksplorasi alam hijau Bandung Barat.',
                'description' => 'Paket premium untuk traveler yang ingin menikmati eksplorasi alam, glamping, dan pengalaman wisata yang lebih eksklusif.',
                'featured_image' => 'product-12.jpg',
                'base_price' => 120.00,
                'sale_price' => 80.00,
                'duration_days' => 3,
                'quota' => 6,
                'location' => 'Bandung Barat',
                'is_featured' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'lombok-island-trip',
                'title' => 'Bandung Barat Leisure Trip',
                'category' => 'Beach',
                'summary' => 'Taman, bukit, dan itinerary santai untuk liburan yang berkesan.',
                'description' => 'Trip santai dengan kombinasi taman wisata, bukit, dan aktivitas keluarga terbaik di Bandung Barat.',
                'featured_image' => 'product-6.jpg',
                'base_price' => 120.00,
                'sale_price' => null,
                'duration_days' => 3,
                'quota' => 10,
                'location' => 'Bandung Barat',
                'is_featured' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
