@extends('layouts.app')

@section('title', 'Exflore KBB - Website Pemesanan Wisata')

@section('content')
@php $heroImage = str_contains($contactContent['hero_image'], 'assets/') ? asset($contactContent['hero_image']) : asset('storage/' . $contactContent['hero_image']); @endphp
<div class="hero-wrap hero-bread" style="background-image: url('{{ $heroImage }}');"><div class="container"><div class="row no-gutters slider-text align-items-center justify-content-center"><div class="col-md-9 ftco-animate text-center"><p class="breadcrumbs"><span class="mr-2"><a href="{{ route('home') }}">Home</a></span> <span>{{ $contactContent['hero_breadcrumb'] }}</span></p><h1 class="mb-0 bread">{{ $contactContent['hero_title'] }}</h1></div></div></div></div>
<section class="ftco-section contact-section bg-light"><div class="container"><div class="row d-flex mb-5 contact-info"><div class="w-100"></div>@foreach ($contactContent['info_cards'] as $card)<div class="col-md-3 d-flex"><div class="info bg-white p-4"><p><span>{{ $card['label'] }}:</span> @if (! empty($card['link']))<a href="{{ $card['link'] }}">{{ $card['value'] }}</a>@else{{ $card['value'] }}@endif</p></div></div>@endforeach</div><div class="row block-9"><div class="col-md-6 order-md-last d-flex"><form action="#" class="bg-white p-5 contact-form"><h3 class="mb-4">{{ $contactContent['form_title'] }}</h3><div class="form-group"><input type="text" class="form-control" placeholder="{{ $contactContent['placeholders']['name'] }}"></div><div class="form-group"><input type="text" class="form-control" placeholder="{{ $contactContent['placeholders']['email'] }}"></div><div class="form-group"><input type="text" class="form-control" placeholder="{{ $contactContent['placeholders']['subject'] }}"></div><div class="form-group"><textarea cols="30" rows="7" class="form-control" placeholder="{{ $contactContent['placeholders']['message'] }}"></textarea></div><div class="form-group"><input type="submit" value="{{ $contactContent['button_label'] }}" class="btn btn-primary py-3 px-5"></div></form></div><div class="col-md-6 d-flex"><div id="map" class="bg-white"></div></div></div></div></section>
@endsection
