@extends('admin.layouts.app')
@section('title', 'Edit About')
@section('page_title', 'Edit About')
@section('page_description', 'Atur judul, gambar, counter, dan isi halaman About.')
@section('page_actions')<a class="btn btn-secondary" href="{{ route('about') }}" target="_blank">Lihat About</a>@endsection
@section('content')
<form method="POST" action="{{ route('admin.content.about.update') }}" enctype="multipart/form-data" class="stack">@csrf @method('PUT')
<section class="panel"><div class="panel-body form-grid"><div class="field"><label>Hero Title</label><input data-live-target="about-title" type="text" name="hero_title" value="{{ old('hero_title', $about['hero_title']) }}"></div><div class="field"><label>Breadcrumb</label><input type="text" name="hero_breadcrumb" value="{{ old('hero_breadcrumb', $about['hero_breadcrumb']) }}"></div><div class="field"><label>Upload Hero Image</label><input type="file" name="hero_image_upload" accept="image/png,image/jpeg,image/webp"></div><div class="field"><label>Upload Intro Image</label><input type="file" name="intro_image_upload" accept="image/png,image/jpeg,image/webp"></div><div class="field-full"><label>Intro Heading</label><input data-live-target="about-heading" type="text" name="intro_heading" value="{{ old('intro_heading', $about['intro_heading']) }}"></div><div class="field-full"><label>Paragraph 1</label><textarea data-live-target="about-text-1" name="paragraph_1">{{ old('paragraph_1', $about['paragraph_1']) }}</textarea></div><div class="field-full"><label>Paragraph 2</label><textarea data-live-target="about-text-2" name="paragraph_2">{{ old('paragraph_2', $about['paragraph_2']) }}</textarea></div><div class="field"><label>Video URL</label><input type="text" name="video_url" value="{{ old('video_url', $about['video_url']) }}"></div><div class="field"><label>CTA Route</label><input type="text" name="cta_route" value="{{ old('cta_route', $about['cta_route']) }}"></div><div class="field"><label>CTA Label</label><input data-live-target="about-cta" type="text" name="cta_label" value="{{ old('cta_label', $about['cta_label']) }}"></div></div></section>
<section class="panel"><div class="panel-body stack"><h2 style="margin:0;">Counters</h2>@foreach ($about['counters'] as $index => $counter)<div class="form-grid"><div class="field"><label>Angka {{ $index + 1 }}</label><input type="text" name="counters[{{ $index }}][number]" value="{{ old("counters.$index.number", $counter['number']) }}"></div><div class="field"><label>Label {{ $index + 1 }}</label><input type="text" name="counters[{{ $index }}][label]" value="{{ old("counters.$index.label", $counter['label']) }}"></div></div>@endforeach<div class="field"><label>Upload Background Counter</label><input type="file" name="counters_background_upload" accept="image/png,image/jpeg,image/webp"></div></div></section>
<section class="panel"><div class="panel-body form-grid"><div class="field"><label>Testimony Subheading</label><input type="text" name="testimony[subheading]" value="{{ old('testimony.subheading', $about['testimony']['subheading']) }}"></div><div class="field"><label>Newsletter Title</label><input type="text" name="newsletter[title]" value="{{ old('newsletter.title', $about['newsletter']['title']) }}"></div><div class="field-full"><label>Testimony Title</label><input type="text" name="testimony[title]" value="{{ old('testimony.title', $about['testimony']['title']) }}"></div><div class="field-full"><label>Testimony Text</label><textarea name="testimony[text]">{{ old('testimony.text', $about['testimony']['text']) }}</textarea></div><div class="field-full"><label>Newsletter Text</label><textarea name="newsletter[text]">{{ old('newsletter.text', $about['newsletter']['text']) }}</textarea></div><div class="field"><label>Newsletter Placeholder</label><input type="text" name="newsletter[placeholder]" value="{{ old('newsletter.placeholder', $about['newsletter']['placeholder']) }}"></div><div class="field"><label>Newsletter Button</label><input type="text" name="newsletter[button_label]" value="{{ old('newsletter.button_label', $about['newsletter']['button_label']) }}"></div></div></section>
<section class="panel"><div class="panel-body"><h2 style="margin-top:0;">Preview</h2><div class="stack"><strong id="about-title-preview">{{ $about['hero_title'] }}</strong><div id="about-heading-preview">{{ $about['intro_heading'] }}</div><div class="muted" id="about-text-1-preview">{{ $about['paragraph_1'] }}</div><div class="muted" id="about-text-2-preview">{{ $about['paragraph_2'] }}</div><span class="badge" id="about-cta-preview">{{ $about['cta_label'] }}</span></div></div></section>
<div class="actions"><button class="btn btn-primary" type="submit">Simpan About</button></div></form>
<script>document.querySelectorAll('[data-live-target]').forEach((el)=>{const preview=document.getElementById(el.dataset.liveTarget+'-preview'); if(!preview)return; const update=()=>preview.textContent=el.value; el.addEventListener('input',update);});</script>
@endsection
