@extends('admin.layouts.app')
@section('title', 'Edit Contact')
@section('page_title', 'Edit Contact')
@section('page_description', 'Atur informasi kontak, heading, dan form halaman Contact.')
@section('page_actions')<a class="btn btn-secondary" href="{{ route('contact') }}" target="_blank">Lihat Contact</a>@endsection
@section('content')
<form method="POST" action="{{ route('admin.content.contact.update') }}" enctype="multipart/form-data" class="stack">@csrf @method('PUT')
<section class="panel"><div class="panel-body form-grid"><div class="field"><label>Hero Title</label><input data-live-target="contact-title" type="text" name="hero_title" value="{{ old('hero_title', $contact['hero_title']) }}"></div><div class="field"><label>Breadcrumb</label><input type="text" name="hero_breadcrumb" value="{{ old('hero_breadcrumb', $contact['hero_breadcrumb']) }}"></div><div class="field"><label>Form Title</label><input data-live-target="contact-form-title" type="text" name="form_title" value="{{ old('form_title', $contact['form_title']) }}"></div><div class="field"><label>Button Label</label><input data-live-target="contact-button" type="text" name="button_label" value="{{ old('button_label', $contact['button_label']) }}"></div><div class="field"><label>Upload Hero Image</label><input type="file" name="hero_image_upload" accept="image/png,image/jpeg,image/webp"></div></div></section>
<section class="panel"><div class="panel-body stack"><h2 style="margin:0;">Info Cards</h2>@foreach ($contact['info_cards'] as $index => $card)<div class="form-grid"><div class="field"><label>Label {{ $index + 1 }}</label><input type="text" name="info_cards[{{ $index }}][label]" value="{{ old("info_cards.$index.label", $card['label']) }}"></div><div class="field"><label>Value {{ $index + 1 }}</label><input type="text" name="info_cards[{{ $index }}][value]" value="{{ old("info_cards.$index.value", $card['value']) }}"></div><div class="field-full"><label>Link {{ $index + 1 }}</label><input type="text" name="info_cards[{{ $index }}][link]" value="{{ old("info_cards.$index.link", $card['link']) }}"></div></div>@endforeach</div></section>
<section class="panel"><div class="panel-body form-grid"><div class="field"><label>Placeholder Name</label><input type="text" name="placeholders[name]" value="{{ old('placeholders.name', $contact['placeholders']['name']) }}"></div><div class="field"><label>Placeholder Email</label><input type="text" name="placeholders[email]" value="{{ old('placeholders.email', $contact['placeholders']['email']) }}"></div><div class="field"><label>Placeholder Subject</label><input type="text" name="placeholders[subject]" value="{{ old('placeholders.subject', $contact['placeholders']['subject']) }}"></div><div class="field"><label>Placeholder Message</label><input type="text" name="placeholders[message]" value="{{ old('placeholders.message', $contact['placeholders']['message']) }}"></div></div></section>
<section class="panel"><div class="panel-body"><h2 style="margin-top:0;">Preview</h2><div class="stack"><strong id="contact-title-preview">{{ $contact['hero_title'] }}</strong><div id="contact-form-title-preview">{{ $contact['form_title'] }}</div><span class="badge" id="contact-button-preview">{{ $contact['button_label'] }}</span></div></div></section>
<div class="actions"><button class="btn btn-primary" type="submit">Simpan Contact</button></div></form>
<script>document.querySelectorAll('[data-live-target]').forEach((el)=>{const preview=document.getElementById(el.dataset.liveTarget+'-preview'); if(!preview)return; const update=()=>preview.textContent=el.value; el.addEventListener('input',update);});</script>
@endsection
