@extends('admin.layouts.app')
@section('title', 'Edit Footer')
@section('page_title', 'Edit Footer')
@section('page_description', 'Kelola branding, kontak, sosial media, dan link footer.')
@section('content')
<form method="POST" action="{{ route('admin.content.footer.update') }}" class="stack">@csrf @method('PUT')
<section class="panel"><div class="panel-body form-grid"><div class="field"><label>Brand Title</label><input data-live-target="footer-brand" type="text" name="brand_title" value="{{ old('brand_title', $footer['brand_title']) }}"></div><div class="field"><label>Questions Title</label><input type="text" name="questions_title" value="{{ old('questions_title', $footer['questions_title']) }}"></div><div class="field-full"><label>Brand Text</label><textarea data-live-target="footer-text" name="brand_text">{{ old('brand_text', $footer['brand_text']) }}</textarea></div><div class="field"><label>Address</label><input type="text" name="address" value="{{ old('address', $footer['address']) }}"></div><div class="field"><label>Phone</label><input type="text" name="phone" value="{{ old('phone', $footer['phone']) }}"></div><div class="field"><label>Email</label><input type="text" name="email" value="{{ old('email', $footer['email']) }}"></div><div class="field"><label>Copyright</label><input type="text" name="copyright_text" value="{{ old('copyright_text', $footer['copyright_text']) }}"></div></div></section>
<section class="panel"><div class="panel-body stack"><h2 style="margin:0;">Social Links</h2>@foreach ($footer['socials'] as $index => $social)<div class="form-grid"><div class="field"><label>Icon {{ $index + 1 }}</label><input type="text" name="socials[{{ $index }}][icon]" value="{{ old("socials.$index.icon", $social['icon']) }}"></div><div class="field"><label>URL {{ $index + 1 }}</label><input type="text" name="socials[{{ $index }}][url]" value="{{ old("socials.$index.url", $social['url']) }}"></div></div>@endforeach</div></section>
<section class="panel"><div class="panel-body stack"><h2 style="margin:0;">Menu Links</h2>@foreach ($footer['menu_links'] as $index => $link)<div class="form-grid"><div class="field"><label>Label {{ $index + 1 }}</label><input type="text" name="menu_links[{{ $index }}][label]" value="{{ old("menu_links.$index.label", $link['label']) }}"></div><div class="field"><label>Route {{ $index + 1 }}</label><input type="text" name="menu_links[{{ $index }}][route]" value="{{ old("menu_links.$index.route", $link['route']) }}"></div></div>@endforeach</div></section>
<section class="panel"><div class="panel-body form-grid">@foreach ($footer['help_links_left'] as $index => $item)<div class="field"><label>Help Left {{ $index + 1 }}</label><input type="text" name="help_links_left[{{ $index }}]" value="{{ old("help_links_left.$index", $item) }}"></div>@endforeach @foreach ($footer['help_links_right'] as $index => $item)<div class="field"><label>Help Right {{ $index + 1 }}</label><input type="text" name="help_links_right[{{ $index }}]" value="{{ old("help_links_right.$index", $item) }}"></div>@endforeach</div></section>
<section class="panel"><div class="panel-body"><h2 style="margin-top:0;">Preview</h2><div class="stack"><strong id="footer-brand-preview">{{ $footer['brand_title'] }}</strong><div class="muted" id="footer-text-preview">{{ $footer['brand_text'] }}</div></div></div></section>
<div class="actions"><button class="btn btn-primary" type="submit">Simpan Footer</button></div></form>
<script>document.querySelectorAll('[data-live-target]').forEach((el)=>{const preview=document.getElementById(el.dataset.liveTarget+'-preview'); if(!preview)return; const update=()=>preview.textContent=el.value; el.addEventListener('input',update);});</script>
@endsection
