@extends('admin.layouts.app')

@section('title', 'Edit Homepage')
@section('page_title', 'Edit Homepage')
@section('page_description', 'Kelola konten halaman awal customer dengan tab per section dan preview live.')
@section('page_actions')
  <a class="btn btn-secondary" href="{{ route('home') }}" target="_blank">Lihat Homepage</a>
@endsection

@section('content')
<form method="POST" action="{{ route('admin.homepage.update') }}" enctype="multipart/form-data" class="split" style="grid-template-columns:1.35fr .65fr; align-items:start;">@csrf @method('PUT')
  <div class="stack">
    <div class="actions" id="home-tabs">
      <button class="btn btn-primary" type="button" data-tab="hero">Hero</button>
      <button class="btn btn-ghost" type="button" data-tab="services">Services</button>
      <button class="btn btn-ghost" type="button" data-tab="categories">Categories</button>
      <button class="btn btn-ghost" type="button" data-tab="featured">Featured</button>
      <button class="btn btn-ghost" type="button" data-tab="newsletter">Newsletter</button>
    </div>

    <section class="panel home-tab" data-panel="hero"><div class="panel-body stack"><h2 style="margin:0;">Hero Slides</h2>@foreach ($homepage['hero_slides'] as $index => $slide)<div class="panel" style="background:#fff;"><div class="panel-body form-grid"><div class="field"><label>Judul Slide {{ $index + 1 }}</label><input data-live-target="hero-title-{{ $index }}" type="text" name="hero_slides[{{ $index }}][title]" value="{{ old("hero_slides.$index.title", $slide['title']) }}"></div><div class="field"><label>Tombol</label><input data-live-target="hero-button-{{ $index }}" type="text" name="hero_slides[{{ $index }}][button]" value="{{ old("hero_slides.$index.button", $slide['button']) }}"></div><div class="field-full"><label>Subtitle</label><textarea data-live-target="hero-subtitle-{{ $index }}" name="hero_slides[{{ $index }}][subtitle]">{{ old("hero_slides.$index.subtitle", $slide['subtitle']) }}</textarea></div><div class="field"><label>Route Tombol</label><input type="text" name="hero_slides[{{ $index }}][button_route]" value="{{ old("hero_slides.$index.button_route", $slide['button_route']) }}"></div><div class="field"><label>Upload Gambar</label><input type="file" name="hero_slide_uploads[{{ $index }}]" accept="image/png,image/jpeg,image/webp"></div></div></div>@endforeach</div></section>

    <section class="panel home-tab" data-panel="services" style="display:none;"><div class="panel-body stack"><h2 style="margin:0;">Service Features</h2>@foreach ($homepage['service_features'] as $index => $feature)<div class="panel" style="background:#fff;"><div class="panel-body form-grid"><div class="field"><label>Judul</label><input type="text" name="service_features[{{ $index }}][title]" value="{{ old("service_features.$index.title", $feature['title']) }}"></div><div class="field"><label>Icon Class</label><input type="text" name="service_features[{{ $index }}][icon]" value="{{ old("service_features.$index.icon", $feature['icon']) }}"></div><div class="field"><label>Background Class</label><input type="text" name="service_features[{{ $index }}][bg_class]" value="{{ old("service_features.$index.bg_class", $feature['bg_class']) }}"></div><label class="field checkbox"><input type="checkbox" name="service_features[{{ $index }}][is_active]" value="1" {{ old("service_features.$index.is_active", $feature['is_active']) ? 'checked' : '' }}><span>Icon aktif</span></label><div class="field-full"><label>Teks</label><textarea name="service_features[{{ $index }}][text]">{{ old("service_features.$index.text", $feature['text']) }}</textarea></div></div></div>@endforeach</div></section>

    <section class="panel home-tab" data-panel="categories" style="display:none;"><div class="panel-body stack"><h2 style="margin:0;">Category Showcase</h2><div class="form-grid"><div class="field"><label>Judul Utama</label><input type="text" name="category_showcase[main_title]" value="{{ old('category_showcase.main_title', $homepage['category_showcase']['main_title']) }}"></div><div class="field"><label>Route Tombol</label><input type="text" name="category_showcase[button_route]" value="{{ old('category_showcase.button_route', $homepage['category_showcase']['button_route']) }}"></div><div class="field-full"><label>Teks Utama</label><textarea name="category_showcase[main_text]">{{ old('category_showcase.main_text', $homepage['category_showcase']['main_text']) }}</textarea></div><div class="field"><label>Label Tombol</label><input type="text" name="category_showcase[button_label]" value="{{ old('category_showcase.button_label', $homepage['category_showcase']['button_label']) }}"></div><div class="field"><label>Upload Gambar Utama</label><input type="file" name="category_image_uploads[main_image]" accept="image/png,image/jpeg,image/webp"></div></div>@foreach ($homepage['category_showcase']['cards'] as $index => $card)<div class="form-grid"><div class="field"><label>Judul Kartu {{ $index + 1 }}</label><input type="text" name="category_showcase[cards][{{ $index }}][title]" value="{{ old("category_showcase.cards.$index.title", $card['title']) }}"></div><div class="field"><label>Upload Gambar</label><input type="file" name="category_image_uploads[cards][{{ $index }}]" accept="image/png,image/jpeg,image/webp"></div></div>@endforeach</div></section>

    <section class="panel home-tab" data-panel="featured" style="display:none;"><div class="panel-body form-grid"><div class="field"><label>Featured Subheading</label><input type="text" name="featured_section[subheading]" value="{{ old('featured_section.subheading', $homepage['featured_section']['subheading']) }}"></div><div class="field"><label>Featured Route</label><input type="text" name="featured_section[button_route]" value="{{ old('featured_section.button_route', $homepage['featured_section']['button_route']) }}"></div><div class="field-full"><label>Featured Title</label><input type="text" name="featured_section[title]" value="{{ old('featured_section.title', $homepage['featured_section']['title']) }}"></div><div class="field-full"><label>Featured Text</label><textarea name="featured_section[text]">{{ old('featured_section.text', $homepage['featured_section']['text']) }}</textarea></div><div class="field"><label>Featured Button Label</label><input type="text" name="featured_section[button_label]" value="{{ old('featured_section.button_label', $homepage['featured_section']['button_label']) }}"></div></div></section>

    <section class="panel home-tab" data-panel="newsletter" style="display:none;"><div class="panel-body form-grid"><div class="field-full"><label>Newsletter Title</label><input data-live-target="newsletter-title" type="text" name="newsletter[title]" value="{{ old('newsletter.title', $homepage['newsletter']['title']) }}"></div><div class="field-full"><label>Newsletter Text</label><textarea data-live-target="newsletter-text" name="newsletter[text]">{{ old('newsletter.text', $homepage['newsletter']['text']) }}</textarea></div><div class="field"><label>Input Placeholder</label><input type="text" name="newsletter[placeholder]" value="{{ old('newsletter.placeholder', $homepage['newsletter']['placeholder']) }}"></div><div class="field"><label>Button Label</label><input data-live-target="newsletter-button" type="text" name="newsletter[button_label]" value="{{ old('newsletter.button_label', $homepage['newsletter']['button_label']) }}"></div></div></section>

    <div class="actions"><button class="btn btn-primary" type="submit">Simpan Perubahan Homepage</button></div>
  </div>

  <aside class="panel"><div class="panel-body stack"><h2 style="margin-top:0;">Preview Live</h2><div style="border-radius:16px; overflow:hidden; border:1px solid var(--line);"><div style="padding:18px; min-height:200px; background:linear-gradient(rgba(0,0,0,.28), rgba(0,0,0,.28)), url('{{ str_contains($homepage['hero_slides'][0]['image'], 'assets/') ? asset($homepage['hero_slides'][0]['image']) : asset('storage/' . $homepage['hero_slides'][0]['image']) }}') center/cover; color:#fff;"><div class="muted" style="color:#e7efe9;">Hero utama</div><h3 id="hero-title-0-preview" style="margin:12px 0 8px;">{{ $homepage['hero_slides'][0]['title'] }}</h3><p id="hero-subtitle-0-preview" style="margin:0 0 12px;">{{ $homepage['hero_slides'][0]['subtitle'] }}</p><span class="btn btn-secondary" id="hero-button-0-preview">{{ $homepage['hero_slides'][0]['button'] }}</span></div></div><div class="panel" style="background:#fff;"><div class="panel-body"><div class="muted">Newsletter</div><strong id="newsletter-title-preview">{{ $homepage['newsletter']['title'] }}</strong><p id="newsletter-text-preview">{{ $homepage['newsletter']['text'] }}</p><span class="badge" id="newsletter-button-preview">{{ $homepage['newsletter']['button_label'] }}</span></div></div></div></aside>
</form>
<script>
  const tabButtons = document.querySelectorAll('#home-tabs [data-tab]');
  const tabPanels = document.querySelectorAll('.home-tab');
  tabButtons.forEach((button) => { button.addEventListener('click', () => { tabButtons.forEach((item) => item.className = 'btn btn-ghost'); button.className = 'btn btn-primary'; tabPanels.forEach((panel) => { panel.style.display = panel.dataset.panel === button.dataset.tab ? 'block' : 'none'; }); }); });
  document.querySelectorAll('[data-live-target]').forEach((input) => { const preview = document.getElementById(input.dataset.liveTarget + '-preview'); if (!preview) return; const sync = () => { preview.textContent = input.value; }; input.addEventListener('input', sync); });
</script>
@endsection
