@extends('admin.layouts.app')
@section('title', 'Tiket Wisata')
@section('page_title', 'Tiket Wisata')
@section('page_description', 'Kelola destinasi tiket wisata yang tampil di halaman customer.')
@section('page_actions')
  <a class="btn btn-primary" href="{{ route('admin.destination-tickets.create') }}">Tambah Tiket Wisata</a>
@endsection
@section('content')
<section class="panel" style="margin-bottom: 18px;"><div class="panel-body"><form method="GET" action="{{ route('admin.destination-tickets.index') }}" class="form-grid"><div class="field"><label for="search">Cari</label><input id="search" type="text" name="search" value="{{ request('search') }}" placeholder="Nama, slug, lokasi"></div><div class="field"><label for="status">Status</label><select id="status" name="status"><option value="">Semua status</option><option value="active" {{ request('status') === 'active' ? 'selected' : '' }}>Aktif</option><option value="inactive" {{ request('status') === 'inactive' ? 'selected' : '' }}>Nonaktif</option></select></div><div class="field"><label for="sort_info">Urutan</label><input id="sort_info" type="text" value="Berdasarkan sort order lalu nama" readonly></div><div class="field" style="justify-content:end;"><label>&nbsp;</label><div class="actions"><button class="btn btn-primary" type="submit">Filter</button><a class="btn btn-ghost" href="{{ route('admin.destination-tickets.index') }}">Reset</a></div></div></form></div></section>
<section class="panel"><div class="panel-body"><div class="table-wrap"><table><thead><tr><th>Destinasi</th><th>Lokasi</th><th>Harga tiket</th><th>Urutan</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse ($destinationTickets as $destinationTicket)<tr><td><div style="display:flex; gap:12px; align-items:flex-start;">@if ($destinationTicket->image_url)<img src="{{ $destinationTicket->image_url }}" alt="{{ $destinationTicket->name }}" style="width:64px; height:64px; object-fit:cover; border-radius:12px; border:1px solid var(--line);">@endif<div><strong>{{ $destinationTicket->name }}</strong><div class="muted">/{{ $destinationTicket->slug }}</div></div></div></td><td>{{ $destinationTicket->location ?: '-' }}</td><td>${{ number_format((float) $destinationTicket->price, 2) }}</td><td>{{ $destinationTicket->sort_order }}</td><td><span class="badge {{ $destinationTicket->is_active ? 'badge-success' : 'badge-neutral' }}">{{ $destinationTicket->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td><div class="actions"><a class="btn btn-secondary" href="{{ route('admin.destination-tickets.show', $destinationTicket) }}">Lihat</a><a class="btn btn-ghost" href="{{ route('admin.destination-tickets.edit', $destinationTicket) }}">Edit</a></div></td></tr>@empty<tr><td colspan="6" class="muted">Belum ada data tiket wisata.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $destinationTickets->links() }}</div></div></section>
@endsection
