@extends('admin.layouts.app')
@section('title', 'Paket Kuliner')
@section('page_title', 'Paket Kuliner')
@section('page_description', 'Kelola paket makanan yang tersedia untuk pemesanan kuliner customer.')
@section('page_actions')
  <a class="btn btn-secondary" href="{{ route('admin.culinary-venues.index') }}">Kelola Rumah Makan</a>
  <a class="btn btn-primary" href="{{ route('admin.culinary-packages.create') }}">Tambah Paket Kuliner</a>
@endsection
@section('content')
<section class="panel" style="margin-bottom: 18px;"><div class="panel-body"><form method="GET" action="{{ route('admin.culinary-packages.index') }}" class="form-grid"><div class="field"><label for="search">Cari</label><input id="search" type="text" name="search" value="{{ request('search') }}" placeholder="Nama paket, slug, rumah makan"></div><div class="field"><label for="culinary_venue_id">Rumah Makan</label><select id="culinary_venue_id" name="culinary_venue_id"><option value="">Semua rumah makan</option>@foreach ($culinaryVenues as $venue)<option value="{{ $venue->id }}" {{ (string) request('culinary_venue_id') === (string) $venue->id ? 'selected' : '' }}>{{ $venue->name }}</option>@endforeach</select></div><div class="field"><label for="status">Status</label><select id="status" name="status"><option value="">Semua status</option><option value="active" {{ request('status') === 'active' ? 'selected' : '' }}>Aktif</option><option value="inactive" {{ request('status') === 'inactive' ? 'selected' : '' }}>Nonaktif</option></select></div><div class="field" style="justify-content:end;"><label>&nbsp;</label><div class="actions"><button class="btn btn-primary" type="submit">Filter</button><a class="btn btn-ghost" href="{{ route('admin.culinary-packages.index') }}">Reset</a></div></div></form></div></section>
<section class="panel"><div class="panel-body"><div class="table-wrap"><table><thead><tr><th>Paket</th><th>Rumah Makan</th><th>Harga / orang</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse ($culinaryPackages as $culinaryPackage)<tr><td><strong>{{ $culinaryPackage->name }}</strong><div class="muted">/{{ $culinaryPackage->slug }}</div></td><td>{{ $culinaryPackage->culinaryVenue?->name ?: '-' }}</td><td>${{ number_format((float) $culinaryPackage->price_per_person, 2) }}</td><td><span class="badge {{ $culinaryPackage->is_active ? 'badge-success' : 'badge-neutral' }}">{{ $culinaryPackage->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td><div class="actions"><a class="btn btn-secondary" href="{{ route('admin.culinary-packages.show', $culinaryPackage) }}">Lihat</a><a class="btn btn-ghost" href="{{ route('admin.culinary-packages.edit', $culinaryPackage) }}">Edit</a></div></td></tr>@empty<tr><td colspan="5" class="muted">Belum ada paket kuliner.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $culinaryPackages->links() }}</div></div></section>
@endsection
