@extends('admin.layouts.app')
@section('title', 'Detail Penginapan')
@section('page_title', $accommodation->name)
@section('page_description', 'Lihat informasi lengkap penginapan yang tersedia untuk booking.')
@section('page_actions')
  <a class="btn btn-ghost" href="{{ route('admin.accommodations.edit', $accommodation) }}">Edit</a>
  <a class="btn btn-secondary" href="{{ route('admin.accommodations.index') }}">Kembali</a>
@endsection
@section('content')
<div class="split"><section class="panel"><div class="panel-body stack"><div><span class="muted">Nama</span><br><strong>{{ $accommodation->name }}</strong></div><div><span class="muted">Slug</span><br>/{{ $accommodation->slug }}</div><div><span class="muted">Tipe</span><br>{{ $accommodation->type_label }}</div><div><span class="muted">Lokasi</span><br>{{ $accommodation->location ?: '-' }}</div><div><span class="muted">Deskripsi</span><br>{{ $accommodation->description ?: '-' }}</div></div></section><section class="panel"><div class="panel-body stack"><div><span class="muted">Harga / malam</span><br><strong>${{ number_format((float) $accommodation->price_per_night, 2) }}</strong></div><div><span class="muted">Kapasitas</span><br>{{ $accommodation->capacity }} orang</div><div><span class="muted">Status</span><br><span class="badge {{ $accommodation->is_active ? 'badge-success' : 'badge-neutral' }}">{{ $accommodation->is_active ? 'Aktif' : 'Nonaktif' }}</span></div><div><span class="muted">Total booking terkait</span><br>{{ $accommodation->booking_accommodations_count }}</div>@if ($accommodation->image_url)<div><span class="muted">Gambar</span><br><img src="{{ $accommodation->image_url }}" alt="{{ $accommodation->name }}" style="width:100%; max-width:320px; border-radius:16px; border:1px solid var(--line); margin-top:8px;"></div>@endif<form method="POST" action="{{ route('admin.accommodations.destroy', $accommodation) }}">@csrf @method('DELETE')<button class="btn btn-danger" type="submit" onclick="return confirm('Hapus penginapan ini?')">Hapus Penginapan</button></form></div></section></div>
<section class="panel" style="margin-top: 18px;"><div class="panel-body"><h2 style="margin-top: 0;">Riwayat Booking Penginapan</h2><div class="table-wrap"><table><thead><tr><th>Kode Booking</th><th>Pelanggan</th><th>Tanggal</th><th>Status</th><th>Total Penginapan</th></tr></thead><tbody>@forelse ($accommodation->bookingAccommodations as $history)<tr><td>@if ($history->booking)<a href="{{ route('admin.bookings.show', $history->booking) }}">{{ $history->booking->booking_code }}</a>@else - @endif</td><td>{{ $history->booking?->customer_full_name ?: '-' }}</td><td>{{ $history->booking?->created_at?->format('d M Y H:i') ?: '-' }}</td><td>{{ $history->booking?->status_badge ?: '-' }}</td><td>{{ $history->formatted_line_total }}</td></tr>@empty<tr><td colspan="5" class="muted">Belum ada booking yang memakai penginapan ini.</td></tr>@endforelse</tbody></table></div></div></section>
@endsection
