@extends('admin.layouts.app')
@section('title', 'Penginapan')
@section('page_title', 'Penginapan')
@section('page_description', 'Kelola hotel, villa, dan homestay yang tersedia untuk customer.')
@section('page_actions')
  <a class="btn btn-primary" href="{{ route('admin.accommodations.create') }}">Tambah Penginapan</a>
@endsection
@section('content')
<section class="panel" style="margin-bottom: 18px;"><div class="panel-body"><form method="GET" action="{{ route('admin.accommodations.index') }}" class="form-grid"><div class="field"><label for="search">Cari</label><input id="search" type="text" name="search" value="{{ request('search') }}" placeholder="Nama, slug, lokasi"></div><div class="field"><label for="type">Tipe</label><select id="type" name="type"><option value="">Semua tipe</option>@foreach ($types as $type)<option value="{{ $type }}" {{ request('type') === $type ? 'selected' : '' }}>{{ ucfirst($type) }}</option>@endforeach</select></div><div class="field"><label for="status">Status</label><select id="status" name="status"><option value="">Semua status</option><option value="active" {{ request('status') === 'active' ? 'selected' : '' }}>Aktif</option><option value="inactive" {{ request('status') === 'inactive' ? 'selected' : '' }}>Nonaktif</option></select></div><div class="field" style="justify-content:end;"><label>&nbsp;</label><div class="actions"><button class="btn btn-primary" type="submit">Filter</button><a class="btn btn-ghost" href="{{ route('admin.accommodations.index') }}">Reset</a></div></div></form></div></section>
<section class="panel"><div class="panel-body"><div class="table-wrap"><table><thead><tr><th>Nama</th><th>Tipe</th><th>Lokasi</th><th>Harga / malam</th><th>Kapasitas</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse ($accommodations as $accommodation)<tr><td><div style="display:flex; gap:12px; align-items:flex-start;">@if ($accommodation->image_url)<img src="{{ $accommodation->image_url }}" alt="{{ $accommodation->name }}" style="width:64px; height:64px; object-fit:cover; border-radius:12px; border:1px solid var(--line);">@endif<div><strong>{{ $accommodation->name }}</strong><div class="muted">/{{ $accommodation->slug }}</div></div></div></td><td>{{ $accommodation->type_label }}</td><td>{{ $accommodation->location ?: '-' }}</td><td>${{ number_format((float) $accommodation->price_per_night, 2) }}</td><td>{{ $accommodation->capacity }} orang</td><td><span class="badge {{ $accommodation->is_active ? 'badge-success' : 'badge-neutral' }}">{{ $accommodation->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td><div class="actions"><a class="btn btn-secondary" href="{{ route('admin.accommodations.show', $accommodation) }}">Lihat</a><a class="btn btn-ghost" href="{{ route('admin.accommodations.edit', $accommodation) }}">Edit</a></div></td></tr>@empty<tr><td colspan="7" class="muted">Belum ada data penginapan.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $accommodations->links() }}</div></div></section>
@endsection
