@extends('admin.layouts.app')
@section('title', 'Paket Wisata')
@section('page_title', 'Paket Wisata')
@section('page_description', 'Kelola semua paket travel yang tampil di storefront.')
@section('page_actions')
  <a class="btn btn-primary" href="{{ route('admin.travel-packages.create') }}">Tambah Paket</a>
@endsection
@section('content')
<section class="panel" style="margin-bottom: 18px;"><div class="panel-body"><form method="GET" action="{{ route('admin.travel-packages.index') }}" class="form-grid"><div class="field"><label for="search">Cari</label><input id="search" type="text" name="search" value="{{ request('search') }}" placeholder="Judul, slug, lokasi"></div><div class="field"><label for="category">Kategori</label><select id="category" name="category"><option value="">Semua kategori</option>@foreach ($categories as $category)<option value="{{ $category }}" {{ request('category') === $category ? 'selected' : '' }}>{{ $category }}</option>@endforeach</select></div><div class="field"><label for="status">Status</label><select id="status" name="status"><option value="">Semua status</option><option value="active" {{ request('status') === 'active' ? 'selected' : '' }}>Aktif</option><option value="inactive" {{ request('status') === 'inactive' ? 'selected' : '' }}>Nonaktif</option></select></div><div class="field" style="justify-content: end;"><label>&nbsp;</label><div class="actions"><button class="btn btn-primary" type="submit">Filter</button><a class="btn btn-ghost" href="{{ route('admin.travel-packages.index') }}">Reset</a></div></div></form></div></section>
<section class="panel"><div class="panel-body"><div class="table-wrap"><table><thead><tr><th>Judul</th><th>Kategori</th><th>Lokasi</th><th>Harga</th><th>Galeri</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse ($packages as $package)<tr><td><div style="display:flex; gap:12px; align-items:flex-start;">@if ($package->image_url)<img src="{{ $package->image_url }}" alt="{{ $package->title }}" style="width:64px; height:64px; object-fit:cover; border-radius:12px; border:1px solid var(--line);">@endif<div><strong>{{ $package->title }}</strong><div class="muted">/{{ $package->slug }}</div></div></div></td><td>{{ $package->category }}</td><td>{{ $package->location ?: '-' }}</td><td>{{ $package->display_price }}</td><td>{{ $package->gallery_images_count }}</td><td><span class="badge {{ $package->is_active ? 'badge-success' : 'badge-neutral' }}">{{ $package->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td><div class="actions"><a class="btn btn-secondary" href="{{ route('admin.travel-packages.show', $package) }}">Lihat</a><a class="btn btn-ghost" href="{{ route('admin.travel-packages.edit', $package) }}">Edit</a></div></td></tr>@empty<tr><td colspan="7" class="muted">Belum ada paket wisata.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $packages->links() }}</div></div></section>
@endsection
