@extends('admin.layouts.app')
@section('title', $travelPackage->title)
@section('page_title', $travelPackage->title)
@section('page_description', 'Detail paket wisata dan ringkasan performanya.')
@section('page_actions')<a class="btn btn-ghost" href="{{ route('admin.travel-packages.edit', $travelPackage) }}">Edit</a><a class="btn btn-secondary" href="{{ route('admin.travel-packages.index') }}">Kembali</a>@endsection
@section('content')
<div class="split">
<section class="panel"><div class="panel-body stack"><div><div class="muted">Slug</div><strong>{{ $travelPackage->slug }}</strong></div><div><div class="muted">Kategori</div><strong>{{ $travelPackage->category }}</strong></div><div><div class="muted">Lokasi</div><strong>{{ $travelPackage->location ?: '-' }}</strong></div><div><div class="muted">Ringkasan</div><div>{{ $travelPackage->summary ?: '-' }}</div></div><div><div class="muted">Deskripsi</div><div>{{ $travelPackage->description ?: '-' }}</div></div>@if ($travelPackage->galleryImages->count())<div><div class="muted">Galeri Paket</div><div style="display:flex; gap:12px; flex-wrap:wrap; margin-top:10px;">@foreach ($travelPackage->galleryImages as $galleryImage)<img src="{{ $galleryImage->image_url }}" alt="Gallery image" style="width:120px; height:90px; object-fit:cover; border-radius:14px; border:1px solid var(--line);">@endforeach</div></div>@endif</div></section>
<section class="panel"><div class="panel-body stack"><div><div class="muted">Harga Dasar</div><strong>${{ number_format((float) $travelPackage->base_price, 2) }}</strong></div><div><div class="muted">Harga Promo</div><strong>{{ $travelPackage->sale_price ? '$' . number_format((float) $travelPackage->sale_price, 2) : '-' }}</strong></div><div><div class="muted">Durasi</div><strong>{{ $travelPackage->duration_days }} hari</strong></div><div><div class="muted">Kuota</div><strong>{{ $travelPackage->quota }}</strong></div><div><div class="muted">Dipakai di booking</div><strong>{{ $travelPackage->booking_items_count }}</strong></div><div><div class="muted">Jumlah galeri</div><strong>{{ $travelPackage->galleryImages->count() }}</strong></div><div class="actions"><form method="POST" action="{{ route('admin.travel-packages.destroy', $travelPackage) }}" onsubmit="return confirm('Hapus paket ini?');">@csrf @method('DELETE')<button class="btn btn-danger" type="submit">Hapus Paket</button></form></div></div></section>
</div>
@endsection
